[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self'; img-src cdn.dummyjson.com https://ipfs.dscvr.one https://media.dscvr.one https://media1.stg.dscvr.one data:; connect-src dummyjson.com https://api.dscvr.one https://api1.stg.dscvr.one https://*.helius-rpc.com; font-src 'self';"
