[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self'; img-src https://cdn.dummyjson.com/* https://*.ipfs.nftstorage.link; connect-src 'self' https://dummyjson.com https://api.dscvr.one https://api1.stg.dscvr.one https://*.helius-rpc.com; font-src 'self';"
