[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self'; img-src https://cdn.dummyjson.com/*; connect-src 'self' https://dummyjson.com ; font-src 'self';"
